### ISSUE TITLE
Add terraform-provider-argocd as an Argolabs project

### ISSUE THREAD

**Issue by blakepettersson** [argoproj-labs/community#10]
Welcome to Argo Project Onboarding!
 
Before submitting the ticket please ensure you understand which [projects](../../community/ecosystem-projects.md) could be added to the Argo community and what the open decision-making process looks like.
 
Once you are ready, please help the reviewer understand your project better by answering the following questions in your onboarding proposal:
 
* [x]  What is your project repository Github URL?
https://github.com/oboukili/terraform-provider-argocd

* [x]  Do you wish to host your project repository on https://github.com/argoproj-labs or https://github.com/argoproj ?
on https://github.com/argoproj-labs

* [x]  Does your project focus on enhancing or providing additional features to one of the existing [core projects](https://github.com/argoproj/argoproj#what-is-argoproj) ? If yes, which of the core projects is your proposed project related to?
It allows Argo CD to be configured through Terraform. 

* [x]  Is it endorsed by any of the Argo subproject maintainers? Please mention sponsors from the subproject.
@wanghong230 

* [x]  How does it align with the goals of the Argo community?
By enabling users that use Terraform to more easily adopt Argo CD

* [x]  Who will maintain the project going forward?
@the-technat, @onematchfox. Perhaps @mkilchhofer and @oboukili? I'm also willing to help out.
 
* [x]  What is your project license?
MPL-2.0

**Comment by wanghong230** [comment]
+1

**Comment by mkilchhofer** [comment]
xref:
- https://github.com/oboukili/terraform-provider-argocd/issues/323

**Comment by todaywasawesome** [comment]
❤️ let's add to Argo lab, at KubeCon we've already referenced it a dozen times.

**Comment by leoluz** [comment]
Repository created:
https://github.com/argoproj-labs/terraform-provider-argocd
Added @blakepettersson as a repository maintainer.

**Comment by mkilchhofer** [comment]
Just for my understanding, why do we need a new repo? Why not transfering the existing one?

When we create a new one, we loose some history (issues, PRs, stars, auto redirects to the new location, ...?)

**Comment by blakepettersson** [comment]
@mkilchhofer good point. The only way for a transfer to can happen though would be for someone with admin rights in both oboukili/terraform-provider-argocd and argoproj-labs to do the transfer. So it would be a matter of adding @leoluz as an admin (or someone else in argoproj-labs with admin rights) to the existing repository, and then the argoproj-labs admin would need to do the transfer to argoproj-labs.

**Comment by mkilchhofer** [comment]
Alright, shall we ask @oboukili if he can add an argoproj admin as a repo admin?

**Comment by oboukili** [comment]
Yes, done I added @leoluz as a repo collaborator, I can't seem to be able to change the access type beyond `collaborator`, I guess because a GH org is needed. I can however move the repository to the argoproj-labs GH org, but I would need to be granted (temporary) repo creation within that org. Let me know once this has been granted.

One thing to check once that's done, according to this [thread](https://discuss.hashicorp.com/t/issue-with-migration-of-terraform-provider-as-developer/41358), there may be an issue with the terraform registry sync to keep in mind.

**Comment by edlee2121** [comment]
See if you can transfer the repo to @leoluz

**Comment by blakepettersson** [comment]
That's also a good option - if the repo ownership is transferred to an individual (in this case @leoluz) then he can then do the migration to argoproj-labs.

**Comment by mkilchhofer** [comment]
We already chatted about this 😆 
> 
![image](https://github.com/argoproj-labs/community/assets/7290987/0dc4fe84-35b5-48f6-a4f0-d1771f361ce3)

I think the crucial point is that HashiCorp have no clear statements how this registry stuff can be migrated in-place. When we move it in 2 steps, requests to the old repo (releases, tags) are redirected twice. No one know if this is supported 🤷 .

> ## Can I change the name of my artifact?
> 
> Once consumers start using your provider, module, or policy library, the name of the artifact must remain constant. Otherwise,  you could break your consumer's Terraform configuration.
> 
> For this reason, we strongly recommend _against_ moving or renaming an existing artifact. Instead, it's often a better choice to create a new repository, representing the new name of your artifact while leaving the old content in place.
> 
> For further help, [reach out to us via email](/terraform/registry#getting-help).
> 
> ## Can I rename the GitHub user or organization that owns my artifact's repository?
> 
> When you change the name of a GitHub user or organization, GitHub automatically redirects requests for the old user or organization to the new one. This means there is no interruption for your artifact's consumers, who can continue using the old name. If you need to change the name of your artifact, [see the above answer](#can-i-change-the-name-of-my-artifact).
> 
> 
> If you have changed your publishing Github user or organization name, we _recommend reclaiming_ any names you previously published from. If someone else claims your old user or organization name, they could build repositories that "capture" any redirected requests from the Registry. At that point, your consumers would be unable to download your artifact.
>
> Source: https://developer.hashicorp.com/terraform/registry/faq#can-i-change-the-name-of-my-artifact

Also testing the whole workflow seems to have some caveats as providers cannnot be deleted once published (🙄):
Note

> You cannot un-publish a provider once you publish it to Terraform Registry. As a result, pay very close attention to the GitHub repository and organization you use. For example, consider whether you want to publish as yourself or your company.
>
> Source: https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-release-publish#prerequisites

**Comment by leoluz** [comment]
If @oboukili is going to keep being the main maintainer of the `terraform-provider-argocd` repo once it is migrated, I don't see a big problem with adding him as a member of the `argoproj-labs` org so he can proceed with the migration by himself.
cc @edlee2121 @terrytangyuan @alexmt

**Comment by terrytangyuan** [comment]
Sounds good!

**Comment by zachaller** [comment]
I sent an invite to @oboukili  to be a member of argoproj-labs

**Comment by oboukili** [comment]
Thanks! The provider has been moved, I opened this [HC discuss thread](https://discuss.hashicorp.com/t/transferring-tf-registry-provider-entry-to-a-new-location-upon-gh-repository-ownership-transfer/64591) to hopefully transfer the existing TF registry entry to the new location.
Please note I lost admin permissions on the repository (no more access to GH workflow secrets nor repo access controls).

**Comment by mkilchhofer** [comment]
I think we can close this issue.
@blakepettersson already published the news in #argo-announcements on Slack:
> <img width="761" alt="image" src="https://github.com/user-attachments/assets/a6542d2f-181a-4306-8219-05fad72850d8">

The provider is available in HashiCorp's registry:
https://registry.terraform.io/providers/argoproj-labs/argocd/latest

**Comment by blakepettersson** [comment]
Yes, this is done.
