### ISSUE TITLE
Add GitOps Promoter to ArgoProj Labs

### ISSUE THREAD

**Issue by zachaller** [argoproj-labs/community#11]
Welcome to Argo Project Onboarding!

Before submitting the ticket please ensure you understand which projects could be added to the Argo community and what the open decision-making process looks like.

Once you are ready, please help the reviewer understand your project better by answering the following questions in your onboarding proposal:

 * [x]  What is your project repository Github URL?
https://github.com/zachaller/promoter

 * [x]  Do you wish to host your project repository on https://github.com/argoproj-labs or https://github.com/argoproj ?
on https://github.com/argoproj-labs/gitops-promoter

 * [x]  Does your project focus on enhancing or providing additional features to one of the existing [core projects](https://github.com/argoproj/argoproj#what-is-argoproj) ? If yes, which of the core projects is your proposed project related to?
It will be an add-on tool to allow GitOps Environment Promotions, it will fit in with ArgoCD but is tool agnostic.

 * [x]  Is it endorsed by any of the Argo subproject maintainers? Please mention sponsors from the subproject.
@crenshaw-dev 

 * [x]  How does it align with the goals of the Argo community?
By enabling users to do environment promotions.

 * [x]  Who will maintain the project going forward?
@zachaller and other Intuit devs

 * [x]  What is your project license?
Apache License v2

**Comment by ishitasequeira** [comment]
+1

**Comment by zachaller** [comment]
Transfer is done: https://github.com/argoproj-labs/gitops-promoter
