### ISSUE TITLE
Add argocd-agent to argoproj-labs

### ISSUE THREAD

**Issue by jannfis** [argoproj-labs/community#12]
---
name: argocd-agent onboarding
about: Agent based multi-cluster capabilities for Argo CD
title: "[PROJECT ONBOARDING] argocd-agent"
labels: project onboarding
---

Welcome to Argo Project Onboarding! 

Before submitting the ticket please ensure you understand which [projects](../community/ecosystem-projects.md) could be added to the Argo community and what the open decision-making process looks like. 

Once you are ready, please help the reviewer understand your project better by 
answering the following questions in your onboarding proposal:

- [x] What is your project repository Github URL?

      https://github.com/jannfis/argocd-agent
      
- [x] Do you wish to host your project repository

      https://github.com/argoproj-labs/argocd-agent
      
- [x] Does your project focus on enhancing or providing additional features to one of the existing [core
 projects](https://github.com/argoproj/argoproj#what-is-argoproj) ? If yes, which of the core projects is your proposed project related to?

      Argo CD
- [x] Is it endorsed by any of the Argo subproject maintainers? Please mention sponsors from the subproject.

      @jannfis @jgwest @ishitasequeira

- [x] How does it align with the goals of the Argo community?

      It will enhance scalability and security in multi-cluster management scenarios

- [x] Who will maintain the project going forward?

      @jannfis @jgwest @ishitasequeira

- [x] What is your project license?

      Apache-2.0 License

If you have chosen to propose your project for the https://github.com/argoproj Github org:

- [ ] Please explain how tightly related it is to one of the core projects?
- [ ] Is your project ready? Describe the current user and contributor community (size, activity level, etc.). If you are starting the new project, would you consider contributing the project to https://github.com/argoproj-labs initially.

**Comment by ishitasequeira** [comment]
+1

**Comment by crenshaw-dev** [comment]
+1

**Comment by jannfis** [comment]
Closing this issue as implemented. argocd-agent is now at https://github.com/argoproj-labs/argocd-agent
