### ISSUE TITLE
Maintain argo-python-client and argo-python-dsl

### ISSUE THREAD

**Issue by binarycrayon** [argoproj-labs/community#3]
Hello, after discussing with some members on the community slack channel, I'd like to be added as a maintainer for both argo-python-client and argo-python-dsl.

The original author has ceased development/maintenance on both projects and is not responding to inquiries. I know that there are people who are interested in using Argo workflow come from the python community, so I'd like to facilitate the package development and continue to support the user group. 

Please let me know what needs to be done, thanks!

**Comment by alexec** [comment]
@terrytangyuan can I get your input on this please? I know that Couler support Python and it might be best to avoid having 2 Python clients. @binarycrayon thoughts?

**Comment by terrytangyuan** [comment]
`argo-python-client` may still be useful as a direct Python client of Argo. Though I would ask for specific maintenance plan if anyone is interested in maintaining. From another perspective, I know some users just use k8s Python client directly as well so maintaining a separate Python client might introduce some overhead and may not be as useful.

`argo-python-dsl` is unnecessary though since [Couler](https://github.com/couler-proj/couler) provides same functionalities and more well-maintained and will do our best to support Python users from Argo community going forward. Feel free to report issues [here](https://github.com/couler-proj/couler/issues) if you encounter any problems or missing features.

**Comment by binarycrayon** [comment]
Actually great to know that Couler is under active development and is providing a user-facing workflow API.

I'm still consolidating a longer-term plan for `argo-python-client`, but the current priority are twothings:
 - update the project to the latest version of Argo so user can have access to new features
 - figure out if we can reuse `argo-python` pypi project (Marek got back to me and said he can transfer it to me; I am waiting for that to happen). 

Further down the road, I'd like to look at https://github.com/argoproj-labs/argo-client-gen and see if there is a better way to generate python sdk.

Let me know if you have other suggestions @terrytangyuan @alexec

**Comment by binarycrayon** [comment]
Also on top of that, there are people who are still interested in using lime `argo-python-client` and build their adhoc workflow system on top of that. From their perspective, `argo-python-client` needs to be well maintained so they can trust it.

**Comment by terrytangyuan** [comment]
@binarycrayon Thanks. So I guess the plan is to archive `argo-python-dsl` (which was actually already done) and I'll leave this to Argo team to decide on the next steps for `argo-python-client`. I see you created discussion on Couler repo https://github.com/couler-proj/couler/issues/34 so let's continue discuss questions related to Couler over there.

**Comment by alexec** [comment]
@binarycrayon I've set you up on the @argoproj-labs/sdk-maintainers list so that you have access to the relevant repositories.  I'd like to know if we can come up with a better way to maintain this that is perhaps synced with the OSS release cycle.

**Comment by terrytangyuan** [comment]
@alexec Seems like https://github.com/argoproj-labs/argo-python-dsl is unarchived. Is that intentional? I think we do want to archive the `argo-python-dsl` repo and leave `argo-python-client` as is.

**Comment by binarycrayon** [comment]
I've released update on both argo-python-client and argo-python-dsl. Closing this issue, thanks for having me
