### ISSUE TITLE
Migrating argocd-appsource to argoproj-labs

### ISSUE THREAD

**Issue by aceamarco** [argoproj-labs/community#4]
Welcome to Argo Project Onboarding! 

Before submitting the ticket please ensure you understand which [projects](../../community/ecosystem-projects.md) could be added to the Argo community and what the open decision-making process looks like. 

Once you are ready, please help the reviewer understand your project better by 
answering the following questions in your onboarding proposal:

- [x] What is your project repository Github URL?
My project repo URL is https://github.com/aceamarco/argocd-appsource

- [x] Do you wish to host your project repository https://github.com/argoproj-labs or https://github.com/argoproj ?
I would like to host it on https://github.com/argoproj-labs

- [x] Does your project focus on enhancing or providing additional features to one of the existing [core
 projects](https://github.com/argoproj/argoproj#what-is-argoproj) ? If yes, which of the core projects is your proposed project related to?
My project focuses on enhancing/providing additional features for the core ArgoCD project.

- [x] Is it endorsed by any of the Argo subproject maintainers? Please mention sponsors from the subproject.
My project is endorsed by @alexmt and @jessesuen

- [x] How does it align with the goals of the Argo community?
My project allows larger organizations spread across multiple clusters/restricted namespaces to create ArgoCD applications. This would allow larger teams to adopt ArgoCD into their product workflows without putting stress on an admin team.

- [x] Who will maintain the project going forward?
Either myself @aceamarco or @alexmt

- [x] What is your project license? 
Apache License 2.0

**Comment by crenshaw-dev** [comment]
Project currently looks unmaintained, closing for now.
