### ISSUE TITLE
Add `hera-workflows` to `argoproj-labs`

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/community#5]
Welcome to Argo Project Onboarding!

Before submitting the ticket please ensure you understand which [projects](https://github.com/argoproj-labs/community) could be added to the Argo community and what the open decision-making process looks like.

Once you are ready, please help the reviewer understand your project better by
answering the following questions in your onboarding proposal:

- [x] What is your project repository Github URL ?

- https://github.com/argoproj-labs/hera-workflows
- this project was demoed to the Argo maintainers already but the project code is not public yet

- [x] Do you wish to host your project repository https://github.com/argoproj-labs or https://github.com/argoproj?
- https://github.com/argoproj-labs

- [x] Does your project focus on enhancing or providing additional features to one of the existing core
projects? If yes, which of the core projects is your proposed project related to?

- the project focuses on enhancing accessibility to Argo Workflows. It is specifically tailored towards the scientific community. Hera achieves this by abstracting away specific elements of constructing workflows and allows users to focus on the code for the scientific problem rather than workflow setup. Hera is still, however, flexible, and allows users to specify advanced features such as resources (e.g GPUs), parallelism, etc.

- [x] Is it endorsed by any of the Argo subproject maintainers? Please mention sponsors from the subproject.

- @sarabala1979
- @alexec 
- @jessesuen 
- @todaywasawesome

- [x] How does it align with the goals of the Argo community?

- the goal of the Argo community is to make it easy to use Kubernetes for getting useful work done. Hera supports this mission by making it easy for the scientific community to adopt Argo Workflows through a simple workflow construction and submission interface.

- [x] Who will maintain the project going forward?

- @flaviuvadan, @dynotx, and the Argo community

- [x] What is your project license?

- MIT

- [x] If you have chosen to propose your project for the https://github.com/argoproj Github org please explain how tightly related it is to one of the core projects?

- not applicable as the project is submitted to https://github.com/argoproj-labs

- [x] Is your project ready? Describe the current user and contributor community (size, activity level, etc.). If you are starting the new project, would you consider contributing the project to https://github.com/argoproj-labs initially.

- Hera is a new project that I am submitting to https://github.com/argoproj-labs initially
- community presentation: https://www.youtube.com/watch?v=QETfzfVV-GY

**Comment by alexec** [comment]
I also endorse this.

**Comment by flaviuvadan** [comment]
> I also endorse this.

Thank you, Alex! Adjusted the Issue submission.

**Comment by jessesuen** [comment]
I also would like to sponsor this project.

**Comment by flaviuvadan** [comment]
> I also would like to sponsor this project.

Added you as well, Jesse!

**Comment by todaywasawesome** [comment]
Good project, would be very happy to have it in the labs. +1 you have my vote.

**Comment by flaviuvadan** [comment]
> Good project, would be very happy to have it in the labs. +1 you have my vote.

Thank you, Dan!

**Comment by flaviuvadan** [comment]
The first version of Hera is now public: https://github.com/argoproj-labs/hera-workflows Closing this issue and will re-open in case there's further discussion to be had.
