### ISSUE TITLE
Add argocd-interlace to argoproj-labs

### ISSUE THREAD

**Issue by gajananan** [argoproj-labs/community#8]
Welcome to Argo Project Onboarding!

Before submitting the ticket please ensure you understand which projects could be added to the Argo community and what the open decision-making process looks like.

Once you are ready, please help the reviewer understand your project better by
answering the following questions in your onboarding proposal:

- [x] What is your project repository Github URL ?

- https://github.com/ibm/argocd-interlace

- This project was presented in the Argo Contributor Experience Office Hour (Dec 09) already and to be presented on Dec 16 again and the project code is already public. 

- [x] Do you wish to host your project repository https://github.com/argoproj-labs or https://github.com/argoproj?

- https://github.com/argoproj-labs

- [x] Does your project focus on enhancing or providing additional features to one of the existing core projects? If yes, which of the core projects is your proposed project related to?

- ArgoCD Interlace focuses on enhancing ArgoCD capability from end-to-end software supply chain security viewpoint. It is specifically tailored towards securing ArgoCD GitOps ( i.e., ArgoCD internally builds manifest from source data in Git repository, and auto-sync it with target clusters.). Interlace achieve this by a)  GitOps Source material verification (content signature, commit sign off, etc.), b) Signing manifest generated from ArgoCD, c) producing verifiable transparent evidence records regarding manifest generation (such as the source files for the build, the command to produce the manifest for reproducibility). Interlace is still a pluggable component which does not interfere with existing ArgoCD GitOps.

- [x]  Is it endorsed by any of the Argo subproject maintainers? Please mention sponsors from the subproject.

- @jannfis  would like to sponsor this project  for argoproj-labs.  Thank you @jannfis

- [x]  How does it align with the goals of the Argo community?

- The goal of the Argo community is to make it easy to use Kubernetes for getting useful work done. ArgoCD Interlace supports this mission by creating new opportunity to enable securing applications deployed via ArgoCD GitOps from end-to-end software supply chain security viewpoint. 

- [x] Who will maintain the project going forward?

  @gajananan and @yuji-watanabe-jp  and the Argo community

- [x] What is your project license?
- Apache License 2.0

- [x] If you have chosen to propose your project for the https://github.com/argoproj Github org please explain how tightly related it is to one of the core projects?

- not applicable as the project is submitted to https://github.com/argoproj-labs

- [x] Is your project ready? Describe the current user and contributor community (size, activity level, etc.). If you are starting the new project, would you consider contributing the project to https://github.com/argoproj-labs initially.

- ArgoCD Interlace is a new project that we are submitting to https://github.com/argoproj-labs initially

- community presentation on Dec 09/Dec 16: https://docs.google.com/document/d/1xkoFkVviB70YBzSEa4bDnu-rUZ1sIFtwKKG1Uw8XsY8/edit

**Comment by jannfis** [comment]
Hi!

Apologies for the late reply! I'd like to sponsor this project for argoproj-labs!

Thanks,
Jann

**Comment by jannfis** [comment]
@edlee2121 Can we onboard this project to argoproj-labs please? It does sound really promising, and could help Argo project in the long run with supply chain security - I believe it could evolve into something that's not only good for Argo CD, but might be for Argo Workflows (and possibly others) as well.

**Comment by edlee2121** [comment]
@jannfis Please slack this issue in the argo-maintainers slack channel to keep the maintainers informed and request comments if any. Thank you.

**Comment by gajananan** [comment]
@jannfis Thank you for considering to sponsor this project. @edlee2121 Thank you for trying to inform us.

**Comment by jannfis** [comment]
@gajananan Please start transfering the repository to argoproj-labs

/cc @edlee2121

**Comment by yuji-watanabe-jp** [comment]
@jannfis @edlee2121 Thank you so much. Can you forward the transfer information to me, please. I will start transferring.

**Comment by yuji-watanabe-jp** [comment]
@jannfis @edlee2121 I tried to do transfer from https://github.com/IBM/argocd-interlace, but I am seeing this error. 

<img width="552" alt="スクリーンショット 2022-03-18 12 00 01" src="https://user-images.githubusercontent.com/26372857/158929252-98d203f1-cf35-4158-a835-dd820d7c80d9.png">

Could you give me the permission, please?

**Comment by alexmt** [comment]
Hello @yuji-watanabe-jp , I've invited you to the github org. Once invite is accepted you should be able to transfer the repository.

**Comment by yuji-watanabe-jp** [comment]
@alexmt thank you so much. I could transfer the repository to argoproj-labs successfully. 
https://github.com/argoproj-labs/argocd-interlace

**Comment by jannfis** [comment]
This is awesome news :tada:
