### ISSUE TITLE
CLA needed?

### ISSUE THREAD

**Issue by sambhav** [argoproj-labs/community#9]
Hello,

I am trying to figure out what is needed in order to contribute to argoproj-labs projects specifically https://github.com/argoproj-labs/hera-workflows/

It looks like the current repository has a CLA verifier, but it looks like the argo project has removed the requirement for CLA in https://github.com/argoproj and moved to DCO instead per https://github.com/argoproj/argoproj/blob/master/README.md#news

Is that accurante? If so can the CLA requirements be removed from argoproj-labs organization as well and replaced with DCO? If not, can we provide appropriate links on how to go about signing the corporate CLA?

Thanks

**Comment by agilgur5** [comment]
Projects can technically decide on their own in `argoproj-labs`, but following upstream `argoproj` would be preferred with DCO per https://github.com/argoproj/argoproj/pull/18 & https://github.com/argoproj/argoproj/pull/16

> If so can the CLA requirements be removed from argoproj-labs organization as well and replaced with DCO?

Yes I think that would be appropriate.

> If not, can we provide appropriate links on how to go about signing the corporate CLA?

There seems to be an old, unmerged PR that updated links in #6
